export { AddressComponent } from './src/main/ets/components/addresscomponent/AddressComponent'
export { CommonComponentUIBean } from './src/main/ets/components/addresscomponent/AddressComponentConstant'
export { StandardAddressBeanArray } from './src/main/ets/components/addresscomponent/StandardAddressBeanArray'
export { StandardOrderAddressBean } from './src/main/ets/components/addresscomponent/StandardOrderAddressBean'
